[build]
language = "nodejs"
node_version = "22"
name = "fleet-master"

[env]
DATABASE_URL = "postgres://postgres:uJiIZ3dBbtZvVFS4xy4OVAMyARSCtpUO29QzbdpVNC5lKhC6XPP4xHXFlq8McirV@cqiqcthiovbat5s3onr00kwd:5432/postgres"
NEXTAUTH_SECRET = "7df8a9b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6"
NEXTAUTH_URL = "https://fleet.fieldwaves.com"
